version: "3.7"
services:
  mobileapps:
    build:
      target: development
      context: .
      dockerfile: .pipeline/blubber.yaml
    ports:
      - 8888:8888
    volumes:
      - .:/srv/service
  pagelib:
    build:
      target: development
      context: ./pagelib/
      dockerfile: ../.pipeline/blubber.yaml
    volumes:
      - ./pagelib:/srv/app
