version: "3.7"
services:
  pagelib:
    build:
      context: ./pagelib
      dockerfile: Dockerfile.dev
    volumes:
      - ./pagelib:/srv/app
      - /srv/app/node_modules
    entrypoint: npm run build
